services:
  dlt-booth:
    build:
      context: .
      dockerfile: Dockerfile
    image: dlt-booth
    container_name: dlt-booth
    restart: unless-stopped
    ports:
      - "8085:8085"
    depends_on:
      postgres:
       condition: service_healthy 
    profiles:
      - deploy
    #enables data persistance of key storage and wallet. Remove it to disable data persistance
    volumes:
      - "./docker_data:/data"
    networks:
      - dlt-booth-net
    env_file:
      - ./dlt-booth/env/.env
      
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:16
    ports:
      - "5432:5432"
    env_file: 
      - ./dlt-booth/env/postgres.env
    volumes: 
      - "./dlt-booth/postgresdata:/var/lib/postgresql/data:ro=true,U=true"
      - "./dlt-booth/sql/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql:ro=true,U=true"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dlt_booth
      POSTGRES_DB: dlt_booth
    profiles:
      - dev
      - deploy
    networks:
      - dlt-booth-net
networks:
  dlt-booth-net:
    name: dlt-booth-net