apiVersion: v1
kind: ConfigMap
metadata:
  name: ${DLT_BOOTH_APP_NAME}-config
  namespace: ${DLT_BOOTH_NAMESPACE}
data:
  RUST_BACKTRACE: "1"
  RUST_LOG: debug # info

  # HTTP SERVER CONFIG
  HOST_ADDRESS: 0.0.0.0 # "0.0.0.0" for deploying, "127.0.0.1" for dev
  HOST_PORT: "8085"

  # DLT CONFIG
  NODE_URL: ${DLT_BOOTH_NODE_URL}
  FAUCET_API_ENDPOINT: ${DLT_BOOTH_FAUCET_API_ENDPOINT}
  EXPLORER_URL: ${DLT_BOOTH_EXPLORER_URL}
  RPC_PROVIDER: ${DLT_BOOTH_RPC_PROVIDER}
  CHAIN_ID: "${DLT_BOOTH_CHAIN_ID}"

  # ISSUER CONFIG
  ISSUER_URL: ${DLT_BOOTH_ISSUER_URL}

  # DATABASE CONNECTION CONFIG
  DB_NAME: "dlt_booth"
  DB_USER: ${DLT_BOOTH_DB_USER}
  DB_HOST: ${DLT_BOOTH_APP_NAME}-postgres.${DLT_BOOTH_NAMESPACE}.svc.cluster.local # "postgres" for deploying, "127.0.0.1 " for dev
  DB_PORT: "5432"
  DB_MAX_POOL_SIZE: "16"
---

