apiVersion: v1
kind: Secret
metadata:
  name: docker-registry
  namespace: ${DLT_BOOTH_NAMESPACE}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ${DLT_BOOTH_DOCKER_REGISTRY_CREDENTIALS}
---

