apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: ${DLT_BOOTH_APP_NAME}-postgres
  name: ${DLT_BOOTH_APP_NAME}-postgres
  namespace: ${DLT_BOOTH_NAMESPACE}
spec:
  selector:
    matchLabels:
      app: ${DLT_BOOTH_APP_NAME}-postgres
  serviceName: ${DLT_BOOTH_APP_NAME}-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: ${DLT_BOOTH_APP_NAME}-postgres
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: ${DLT_BOOTH_APP_NAME}-postgres
          image: postgres:${DLT_BOOTH_POSTGRES_IMAGETAG}
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: ${DLT_BOOTH_APP_NAME}-postgres-config
            - secretRef:
                name: ${DLT_BOOTH_APP_NAME}-postgres-secret
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -U $DLT_BOOTH_DB_USER -d dlt_booth
            failureThreshold: 6
            initialDelaySeconds: 30
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          ports:
            - containerPort: 5432
              name: postgres
          resources: {}
          volumeMounts:
            - name: ${DLT_BOOTH_APP_NAME}-postgres-data
              mountPath: "/var/lib/postgresql"
            - name: ${DLT_BOOTH_APP_NAME}-postgres-init
              mountPath: /docker-entrypoint-initdb.d
      restartPolicy: Always
      volumes:
        - name: ${DLT_BOOTH_APP_NAME}-postgres-data
          persistentVolumeClaim:
            claimName: ${DLT_BOOTH_APP_NAME}-postgres-data
        - name: ${DLT_BOOTH_APP_NAME}-postgres-init
          configMap:
            name: ${DLT_BOOTH_APP_NAME}-postgres-init
            items:
              - key: dbinit.sql
                path: dbinit.sql
---

