openapi: '3.0.1'
info:
  version: '1.0.1'
  title: 'DLT Booth API'
  description: This document specifies the REST API for the DLT Booth service.
externalDocs:
  description: Github 
  url: https://github.com/Sedimark/dlt-booth
servers:
- url: http://localhost:1234/api
tags:
- name: Delegated
  description: Operations performed using directly DLT-Booth identity
- name: Utils
  description: Utility operations on DLT and SC Platform
- name: Identity management
  description: Identity management operations
- name: Offering tokenization
  description: Offering tokenization operations
- name: Asset exchange
  description: Asset exchange operations

paths:

################################################################
#                                                              #
#                          Identites                           #
#                                                              #
################################################################

  /delegated/identities:
    post:
      summary: Creates a user identity.
      description: In detail, it creates a new Did embedding in the document an identity public key and an ethereum address securely stored in the booth. Finally reaches the Issuer in order to receive a Verifiable Credential that contains the claims provided in the request body. 
      tags:
      - Delegated
      - Identity management
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Identity'
      responses: 
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CredentialJwt'  
        403:
          description:  The operation should not be executed again without deleting an existing identity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Operation aborted due to an unexpected error during execution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
        - Delegated
        - Identity management
      summary: Delete user identity
      description: In detail, the Booth requests to the issuer to revoke the Verifiable Credential. Finally, the identity stored in the Booth is deleted.
      responses:
        200: 
          description: Deleted
        404:
          description:  Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Operation aborted due to an unexpected error during execution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    get:
      tags:
        - Delegated
        - Identity management
      summary: Get identity
      responses:
        200:
          description: Get credential
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CredentialJwt'  
        404:
          description:  Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Operation aborted due to an unexpected error during execution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      description: If the booth is registered, it returns the JWT payload enveloping a Verifiable Credential
  /delegated/identities/vp:
    post:
      summary: Create VP
      description: Generate a Verifiable Presentation for DLT-Booth Identity.
      tags:
      - Delegated
      - Identity management
      - Asset exchange
      requestBody:
        content:
          application/json:
            schema:
              properties:
                nonce:
                  type: string
              example:
                nonce: "c7400b29-38f4-4915-8026-03ab1b83fe54"
      responses:
        200:
          description: VP Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Jwt'
        404:
          description: Identity not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500: 
          description: Internal Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'             
  /dids/{did}:
    parameters:
      - in: path
        name: did
        required: true
        schema:
          type: string
    get:
      summary: Resolve a DID on the configured verifiable data registry
      description: Given a DID as an input, it queries the configured node as a client to retrieve the current state of the DID Document
      tags:
      - Utils
      - Identity management
      responses:
        200:
          description: Resolved
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/DidDocument'
        500:
          description: Unexpected error
################################################################
#                                                              #
#                          Offerings                           #
#                                                              #
################################################################
  /delegated/offerings:
    post:
      summary: DLT-Booth creates a new offering
      description: Generate a new offering on the configured Factory SC using the identity of the DLT-Booth
      tags:
        - Delegated
        - Offering tokenization
      requestBody:
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/Offering'
                - $ref: '#/components/schemas/OfferingConfig'
      responses:
        201:
          description: NFT created
          content:
            application/json:
              schema:
                type: object
                properties:
                  nftAddress:
                    type: string
              example:
                nftAddress: '0x1a5FdBc891c5D4E6aD68064Ae45D43146D4F9f3a'
        500:
          description: Internal Error
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /offerings:
    get:
          summary: Retrieve the list of available offerings
          description: Reads from the Factory SC and returns the list of addresses of minted NFTs
          tags:
            - Delegated
            - Offering tokenization
          responses:
            200:
              description: "List found: the list of available addresses is returned"
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      addresses:
                        type: array
                        items:
                          type: string
                          example: '0x1a5FdBc891c5D4E6aD68064Ae45D43146D4F9f3a'
            500:
              description: Internal error
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/Error'         
  /offerings/{nftAddress}:
    parameters:
    - in: path
      name: nftAddress
      required: true
      schema:
        type: string
    get:
      summary: Get NFT's offering details, given the NFT address
      description: Returns the details that a specific offering SC can return
      tags:
        - Utils
        - Offering tokenization
      responses:
        200:
          description: Details of the NFT with the provided address
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties: 
                      owner: 
                        type: string
                    example:
                      owner: '0x1a5FdBc891c5D4E6aD68064Ae45D43146D4F9f3a'
                  - $ref: '#/components/schemas/Offering'
        500:
          description: Internal Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
################################################################
#                                                              #
#                          Assets                              #
#                                                              #
################################################################
  /delegated/dt/{nftAddress}:
    parameters:
    - in: path
      name: nftAddress
      required: true
      schema:
        type: string
    post:
      summary: Buy an access token
      description: Buy an access token using DLT-Booth's identity
      tags:
        - Delegated
        - Asset exchange
      responses:
        200:
          description: Purchase successful
          content:
            application/json:
              schema:
                properties:
                  balance:
                    type: integer
                example:
                  balance: 1
        404: 
          description: Address not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        422:
          description: Contract reverted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'    
    get:
      summary: Get token balance
      description: Get the number of access token associated to DLT-Booth Identity
      tags:
        - Delegated
        - Asset exchange
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                properties:
                  balance:
                    type: integer
                example:
                  balance: 1
        404: 
          description: Address not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        422:
          description: Contract reverted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'     
################################################################
#                                                              #
#                          COMPONENTS                          #
#                                                              #
################################################################

components:
  schemas:
    Jwt:
      type: object
      properties:
        jwt: 
          type: string
      example:
        jwt: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30'   
    CredentialJwt:
      type: object
      example: 
       exp: 1775049930
       iss: did:iota:lnk:0x9f42fd4d8712613760030e0ae3bc53decc39b4c889b1ea8db2b1aa007d734893
       nbf: 1743427530
       jti: http://sedimark-issuer:3213/api/credentials/6
       sub: did:iota:lnk:0x73ec91fcd41f30836169f2a7b89166b6ba0093209a03d236e96e79c5e63cb230
       vc:
         '@context':
           - https://www.w3.org/2018/credentials/v1
           - schema: http://schema.org/
         type:
           - VerifiableCredential
           - MarketplaceCredential
         credentialSubject:
           schema:alternateName: someUsername
           schema:memberOf: SEDIMARK marketplace                  
    Credential:
      type: object
      properties:
        alternateName:
          type: string
    Service:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
        serviceEndpoint: 
         type: string  
    Identity:
      type: object
      properties: 
        credential: 
          $ref: '#/components/schemas/Credential'
        services:
          type: array
          items: 
            $ref: '#/components/schemas/Service'
      required:
        - credential
    DidDocument:
      type: object
      example:
        id: did:iota:lnk:0x94e4a3c83a66c2592069e74937887f9f2baf63d96f156d36dabd3f3482395324
        verificationMethod:
          - id: did:iota:lnk:0x94e4a3c83a66c2592069e74937887f9f2baf63d96f156d36dabd3f3482395324#m0K_TnUAenJRKuJ_WU8prsHavPcsACNdRRxk3vPl8Mg
            controller: did:iota:lnk:0x94e4a3c83a66c2592069e74937887f9f2baf63d96f156d36dabd3f3482395324
            type: JsonWebKey2020
            publicKeyJwk:
              kty: OKP
              alg: EdDSA
              kid: m0K_TnUAenJRKuJ_WU8prsHavPcsACNdRRxk3vPl8Mg
              crv: Ed25519
              x: Fl_ytZJjvo6mDXhydn-ah-RLcyWXX1mVJRKKGlJ21Ds
          - id: did:iota:lnk:0x94e4a3c83a66c2592069e74937887f9f2baf63d96f156d36dabd3f3482395324#ethAddress
            controller: did:iota:lnk:0x94e4a3c83a66c2592069e74937887f9f2baf63d96f156d36dabd3f3482395324
            type: EcdsaSecp256k1RecoveryMethod2020
            blockchainAccountId: eip155:1:0xfac00f6ca056036d5163697928aed93ed2490d99
        service:
          - id: did:iota:lnk:0x94e4a3c83a66c2592069e74937887f9f2baf63d96f156d36dabd3f3482395324#service-link
            type: ServiceType
            serviceEndpoint: http://example.com
    Offering:
      type: object
      properties:
        name: 
          type: string
        descriptionUri:
          type: string
        descriptionHash: 
          type: string
      example:
        name: OfferingName
        descriptionUri: http://example.com
        descriptionHash: b133a0c0e9bee3be20163d2ad31d6248db292aa6dcb1ee087a2aa50e0fc75ae2       
    OfferingConfig:
      type: object
      properties:
        symbol:
          type: string
        dtName:
          type: string
        dtSymbol: 
          type: string
        maxSupply: 
          type: integer
      example: 
        symbol: "NFT"
        dtName: "AGREEMENT"
        dtSymbol: "AGREE"
        maxSupply: 10
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: A human readable error message
          type: string